stages:
  - test
  - deploy

test:
  stage: test
  image: node:latest
  script:
    - ./build.sh
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage
      - docs
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - rm -rf public/*
    - cp -r coverage public/coverage
    - cp -r docs public/doc
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - main
